'on':
  workflow_dispatch: ~
  schedule:
  - cron: 35 10 * * 1
name: update
jobs:
  update:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2

    - uses: r-lib/actions/setup-r@v2

    - name: Query dependencies
      run: |
        install.packages('remotes')
        saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
      shell: Rscript {0}

    - name: Restore R package cache
      uses: actions/cache@v2
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds')
          }}
        restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

    - name: Install dependencies
      run: |
        install.packages(c("devtools"))
        devtools::install_deps(dependencies = TRUE)
      shell: Rscript {0}

    - name: Checkout output branch
      uses: actions/checkout@v2
      with:
        ref: output
        path: output

    - name: Update
      run: |
        options(java.parameters = "-Xmx10G")
        devtools::load_all()
        run_cadw_vs_rail()
      shell: Rscript {0}

    - name: Commit new output
      if: github.ref == 'refs/heads/main'
      run: |
        cd output
        git config user.name "Output Update Bot"
        git config user.email "<>"
        git add .
        git commit -m "Updated for new release"
        git push origin output
        cd ..